/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Boundary;

import Control.FileHandler;
import Control.MathFx;
import Entity.ImageData;
import NeuralNetwork.NeuralNetwork;
import AntColonyOptimization.AntColonyOptimization;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import java.util.List;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import org.opencv.core.Core;
import org.opencv.core.Mat;

/**
 *
 * @author Azhary Arliansyah
 */
public class Main extends javax.swing.JFrame {
    
    private List<ImageData> data;
    private List<ImageData> programData;
    private List<ImageRow> rowData;
    private List<OutputNeuronLog> rowLog;
    private DefaultTableModel resultProgramModel;
    private boolean shuffled = false;

    /**
     * Creates new form Home
     */
    public Main() {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        imageListPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        loadImageButton = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        runGaborButton = new javax.swing.JButton();
        jToolBar3 = new javax.swing.JToolBar();
        jPanel4 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        nnResultTable = new javax.swing.JTable();
        neuralNetworkLossChart = new javax.swing.JLabel();
        neuralNetworkProgressBar = new javax.swing.JProgressBar();
        jLabel21 = new javax.swing.JLabel();
        epochField = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        learningRateField = new javax.swing.JTextField();
        runNeuralNetworkButton = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        classifiedRatio = new javax.swing.JLabel();
        splitRatioText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        outputNeuronLogPanel = new javax.swing.JPanel();
        jToolBar4 = new javax.swing.JToolBar();
        jPanel12 = new javax.swing.JPanel();
        jSplitPane6 = new javax.swing.JSplitPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        resultProgramTable = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        loadImageProgramButton = new javax.swing.JButton();
        runNeuralNetworkProgramButton = new javax.swing.JButton();
        runNeuralNetworkAcoProgramButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        jToolBar1.add(jPanel1);

        jTabbedPane1.addTab("Home", jToolBar1);

        jToolBar2.setRollover(true);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane1.setDividerLocation(140);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        imageListPanel.setLayout(new javax.swing.BoxLayout(imageListPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(imageListPanel);

        jSplitPane1.setRightComponent(jScrollPane1);

        loadImageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-add-folder-filled-36.png"))); // NOI18N
        loadImageButton.setText("Load Image");
        loadImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadImageData(evt);
            }
        });

        progressBar.setBackground(new java.awt.Color(0, 204, 51));
        progressBar.setForeground(new java.awt.Color(0, 0, 0));
        progressBar.setToolTipText("");
        progressBar.setString("");
        progressBar.setStringPainted(true);

        runGaborButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-play-24.png"))); // NOI18N
        runGaborButton.setText("Run CBP");
        runGaborButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runCbp(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
            .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(runGaborButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(loadImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(runGaborButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(455, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel3);

        jPanel2.add(jSplitPane1);

        jToolBar2.add(jPanel2);

        jTabbedPane1.addTab("ETL", jToolBar2);

        jToolBar3.setRollover(true);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane2.setDividerLocation(200);

        jSplitPane3.setDividerLocation(700);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Neural Network");

        nnResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Accuracy", null},
                {"Precision", null},
                {"Recall", null},
                {"F-Measure", null}
            },
            new String [] {
                "", "Result"
            }
        ));
        jScrollPane2.setViewportView(nnResultTable);

        neuralNetworkLossChart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        neuralNetworkLossChart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-system-task-100.png"))); // NOI18N

        neuralNetworkProgressBar.setString("");
        neuralNetworkProgressBar.setStringPainted(true);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(neuralNetworkProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(neuralNetworkLossChart, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(neuralNetworkLossChart, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(neuralNetworkProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel21.setText("Epoch");

        epochField.setValue(1000);

        jLabel22.setText("Learning Rate");

        learningRateField.setText("0.55");

        runNeuralNetworkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-play-24.png"))); // NOI18N
        runNeuralNetworkButton.setText("Run Neural Network");
        runNeuralNetworkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runNeuralNetwork(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(epochField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(learningRateField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(26, 26, 26)
                                .addComponent(runNeuralNetworkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(epochField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(runNeuralNetworkButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(learningRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 146, Short.MAX_VALUE))
        );

        jSplitPane3.setLeftComponent(jPanel5);

        jSplitPane2.setRightComponent(jSplitPane3);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Evaluation");

        classifiedRatio.setText("0/0");

        splitRatioText.setText("0.7");

        jLabel14.setText("Split Ratio");

        outputNeuronLogPanel.setLayout(new javax.swing.BoxLayout(outputNeuronLogPanel, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(splitRatioText)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(outputNeuronLogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(classifiedRatio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 555, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(3, 3, 3)
                .addComponent(splitRatioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(classifiedRatio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outputNeuronLogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );

        jSplitPane2.setLeftComponent(jPanel10);

        jPanel4.add(jSplitPane2);

        jToolBar3.add(jPanel4);

        jTabbedPane1.addTab("Classification", jToolBar3);

        jToolBar4.setRollover(true);

        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane6.setDividerLocation(170);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        resultProgramTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Image File", "Actual Label", "Predicted Label", "Correct"
            }
        ));
        jScrollPane4.setViewportView(resultProgramTable);

        jSplitPane6.setRightComponent(jScrollPane4);

        loadImageProgramButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-add-folder-filled-36.png"))); // NOI18N
        loadImageProgramButton.setText("Load Image");
        loadImageProgramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadImageProgramButtonloadImageData(evt);
            }
        });

        runNeuralNetworkProgramButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-play-24.png"))); // NOI18N
        runNeuralNetworkProgramButton.setText("Run Neural Network");
        runNeuralNetworkProgramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runNeuralNetworkProgramButton(evt);
            }
        });

        runNeuralNetworkAcoProgramButton.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        runNeuralNetworkAcoProgramButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-play-24.png"))); // NOI18N
        runNeuralNetworkAcoProgramButton.setText("Run Neural Network + ACO");
        runNeuralNetworkAcoProgramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runNeuralNetworkAcoProgramButton(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadImageProgramButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(runNeuralNetworkProgramButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(runNeuralNetworkAcoProgramButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(loadImageProgramButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(runNeuralNetworkProgramButton)
                .addGap(18, 18, 18)
                .addComponent(runNeuralNetworkAcoProgramButton)
                .addContainerGap(445, Short.MAX_VALUE))
        );

        jSplitPane6.setLeftComponent(jPanel13);

        jPanel12.add(jSplitPane6);

        jToolBar4.add(jPanel12);

        jTabbedPane1.addTab("Program", jToolBar4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Home");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadImageData(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadImageData
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Select Dataset Folder");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            this.imageListPanel.removeAll();
            this.data = new ArrayList<>();
            this.rowData = new ArrayList<>();
            new LoadImageWorker(
                    chooser.getSelectedFile().toString(), 
                    this.imageListPanel,
                    this.data,
                    this.rowData,
                    this.progressBar)
                    .execute();
            
        } 
        else {
            System.out.println("No Selection ");
        }
    }//GEN-LAST:event_loadImageData

    private void runCbp(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runCbp
        
//        this.data.get(0).cbp(8, 1, 8);
        
        new RunCbpWorker(
                    this.imageListPanel,
                    this.data, 
                    this.rowData, 
                    this.progressBar)
                    .execute();
        
    }//GEN-LAST:event_runCbp

    private void loadImageProgramButtonloadImageData(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadImageProgramButtonloadImageData
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Select Dataset Folder");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        
        List<String> filenames = new ArrayList<>();
        List<String> labels = new ArrayList<>();
        this.programData = new ArrayList<>();
        
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            
            FileHandler.read(chooser.getSelectedFile().toString());
            
            int rowCount = 0;
            for (Map.Entry<String, List<String>> ent: 
                FileHandler.LABELS.entrySet()) {
                
                String path = "data/" + ent.getKey();
                for (String filename : ent.getValue()) {
                    
                    filenames.add(filename);
                    labels.add(ent.getKey());
                    
                    try {
                        Image rawImage = ImageIO.read(new File(
                                path + "/" + filename));
                        this.programData.add(new ImageData(
                                path + "/" + filename, ent.getKey()));
                        
                    } catch (IOException ex) {
                        Logger.getLogger(Main.class.getName())
                                .log(Level.SEVERE, null, ex);
                    }
                    rowCount++;
                }
                
            }
            
            this.resultProgramModel = 
                    (DefaultTableModel)this.resultProgramTable.getModel();
            this.resultProgramModel.setRowCount(rowCount);
            this.resultProgramModel.setColumnCount(4);
            
            for (int i = 0; i < rowCount; i++) {
                this.resultProgramModel.setValueAt(filenames.get(i), i, 0);
                this.resultProgramModel.setValueAt(labels.get(i), i, 1);
            }
        } 
        else {
            System.out.println("No Selection ");
        }
    }//GEN-LAST:event_loadImageProgramButtonloadImageData

    private void runNeuralNetworkProgramButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runNeuralNetworkProgramButton
        
        Object[] labels = FileHandler.LABELS.keySet().toArray();
        Map<String, double[]> encodedLabels = new HashMap<>();
        for (int i = 0; i < labels.length; i++) {
            double[] encoded = new double[labels.length];
            encoded[i] = 1.0;
            encodedLabels.put((String)labels[i], encoded);
        }
        
        List<double[]> features = new ArrayList<>();
        List<double[]> classes = new ArrayList<>();
        
        for (ImageData img : this.programData) {
            features.add(img.getCbpData());
            classes.add(encodedLabels.get(img.getLabel()));
        }
        
        double[][] finalFeatures = new double[features.size()][];
        double[][] finalClasses = new double[classes.size()][];
        for (int i = 0; i < features.size(); i++) {
            finalFeatures[i] = features.get(i);
            finalClasses[i] = classes.get(i);
        }
        
        int epoch = Integer.parseInt(String.valueOf(this.epochField.getValue()));
        double learningRate = Double.parseDouble(
                this.learningRateField.getText());
        double splitRatio = Double.parseDouble(this.splitRatioText.getText());
        NeuralNetwork nn = new NeuralNetwork(finalFeatures, finalClasses, 
                labels.length + 2);
        double[][] predicted = nn.predict(finalFeatures);
        for (int i = 0; i < finalFeatures.length; i++) {
            this.resultProgramModel.setValueAt(labels[MathFx
                    .maxIndex(predicted[i])].toString(), i, 2);
            this.resultProgramModel.setValueAt(MathFx.maxIndex(predicted[i]) 
                    == MathFx.maxIndex(finalClasses[i]), i, 3);
        }
    }//GEN-LAST:event_runNeuralNetworkProgramButton

    private void runNeuralNetworkAcoProgramButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runNeuralNetworkAcoProgramButton
        // TODO add your handling code here:
        
    }//GEN-LAST:event_runNeuralNetworkAcoProgramButton

    private void runNeuralNetwork(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runNeuralNetwork

        this.rowLog = new ArrayList<>();
        this.outputNeuronLogPanel.removeAll();

        Object[] labels = FileHandler.LABELS.keySet().toArray();
        Map<String, double[]> encodedLabels = new HashMap<>();
        for (int i = 0; i < labels.length; i++) {
            double[] encoded = new double[labels.length];
            encoded[i] = 1.0;
            encodedLabels.put((String)labels[i], encoded);

            OutputNeuronLog log = new OutputNeuronLog();
            log.labelText.setText((String)labels[i]);
            log.valueText.setText("0.00");
            this.rowLog.add(log);
        }

        for (OutputNeuronLog log : this.rowLog) {
            this.outputNeuronLogPanel.add(log);
        }

        List<double[]> features = new ArrayList<>();
        List<double[]> classes = new ArrayList<>();

        if (!this.shuffled) {
            this.shuffled = true;
            Collections.shuffle(this.data);
        }

        for (ImageData img : this.data) {
            features.add(img.getCbpData());
            classes.add(encodedLabels.get(img.getLabel()));
        }

        double[][] finalFeatures = new double[features.size()][];
        double[][] finalClasses = new double[classes.size()][];
        for (int i = 0; i < features.size(); i++) {
            finalFeatures[i] = features.get(i);
            finalClasses[i] = classes.get(i);
        }
        
        int epoch = Integer.parseInt(String.valueOf(this.epochField.getValue()));
        double learningRate = Double.parseDouble(
            this.learningRateField.getText());
        double splitRatio = Double.parseDouble(this.splitRatioText.getText());
        NeuralNetwork nn = new NeuralNetwork(finalFeatures, finalClasses,
            labels.length + 2, learningRate, epoch, splitRatio);
        new RunNeuralNetworkWorker(nn, this.neuralNetworkProgressBar,
            this.neuralNetworkLossChart, this.rowLog, this.classifiedRatio,
            this.nnResultTable)
        .execute();

    }//GEN-LAST:event_runNeuralNetwork

    class RunNeuralNetworkAcoWorker extends SwingWorker {

        private final NeuralNetwork nn;
        private final JProgressBar progressBar;
        private final javax.swing.JTable resultTable;
        private final int numberOfAnts;
        private final double Q;
        private final double alpha;
        private final double beta;
        private final int iteration;
        private final double[][] features;
        private final double[][] classes;
        private final int numHiddenNeuron;
        private final int epoch;
        private final double splitRatio;
        private final double learningRate;
        private final double evaporationRate;
        
        public RunNeuralNetworkAcoWorker(NeuralNetwork nn, 
                JProgressBar progressBar,  
                javax.swing.JTable resultTable, 
                int numberOfAnts, double Q, double alpha, double beta, 
                double evaporationRate, double rewardFactor,
                int iteration, double[][] features, double[][] classes, 
                int numHiddenNeuron, double learningRate, int epoch, 
                double splitRatio) {
            
            this.nn = nn;
            this.progressBar = progressBar;
            this.resultTable = resultTable;
            this.numberOfAnts = numberOfAnts;
            this.Q = Q;
            this.evaporationRate = evaporationRate;
            this.alpha = alpha;
            this.beta = beta;
            this.iteration = iteration;
            this.features = features;
            this.classes = classes;
            this.numHiddenNeuron = numHiddenNeuron;
            this.epoch = epoch;
            this.splitRatio = splitRatio;
            this.learningRate = learningRate;
        }
        
        @Override
        protected void done() {
           
            JOptionPane.showMessageDialog(null, 
                    "Ant Colony Optimization process is done", "Done", 
                    JOptionPane.INFORMATION_MESSAGE);
            
            repaint();
        }
        
        @Override
        protected Object doInBackground() throws Exception {
            
            AntColonyOptimization aco = new AntColonyOptimization(this.nn, 
                    this.numberOfAnts, this.Q, this.alpha, this.beta, 
                    this.iteration);
            aco.executeAco(this.features, this.classes, this.numHiddenNeuron, 
                    this.learningRate, this.epoch, this.splitRatio, 
                    this.progressBar, this.resultTable);
            return null;
        }
        
    }
    
    
    class RunNeuralNetworkWorker extends SwingWorker {

        private final NeuralNetwork nn;
        private final JProgressBar progressBar;
        private final javax.swing.JLabel lossChart;
        private final javax.swing.JLabel classifiedRatioText;
        private final javax.swing.JTable nnResultTable;
        private final List<OutputNeuronLog> logs;
        
        public RunNeuralNetworkWorker(NeuralNetwork nn, 
                JProgressBar progressBar, javax.swing.JLabel lossChart, 
                List<OutputNeuronLog> logs, 
                javax.swing.JLabel classifiedRatioText, 
                javax.swing.JTable nnResultTable) {
            
            this.nn = nn;
            this.progressBar = progressBar;
            this.lossChart = lossChart;
            this.logs = logs;
            this.classifiedRatioText = classifiedRatioText;
            this.nnResultTable = nnResultTable;
        }
        
        @Override
        protected void done() {
           
            JOptionPane.showMessageDialog(null, 
                    "Neural Network process is done", "Done", 
                    JOptionPane.INFORMATION_MESSAGE);
            
            repaint();
        }
        
        @Override
        protected Object doInBackground() throws Exception {
            this.nn.fit(this.progressBar, this.lossChart, this.logs, 
                    this.classifiedRatioText, this.nnResultTable);
            return null;
        }
        
    }
    
    class LoadImageWorker extends SwingWorker {

        private String path;
        private JPanel imagePanel;
        private JProgressBar progressBar;
        private List<ImageRow> rowData;
        private List<ImageData> data;
        
        public LoadImageWorker(String path, JPanel imagePanel, 
                List<ImageData> data, List<ImageRow> rowData, 
                JProgressBar progressBar) {
            this.path = path;
            this.imagePanel = imagePanel;
            this.progressBar = progressBar;
            this.rowData = rowData;
            this.data = data;
        }
        
        @Override
        protected void done() {
           
            JOptionPane.showMessageDialog(null, 
                    "All image successfully loaded", "Done", 
                    JOptionPane.INFORMATION_MESSAGE);
            for (ImageRow ir : this.rowData) {
                this.imagePanel.add(ir);
            }
            
            repaint();
        }
        
        @Override
        protected Object doInBackground() throws Exception {
            FileHandler.read(this.path);
            
            int loadedFiles = 0;
            for (Map.Entry<String, List<String>> ent: 
                FileHandler.LABELS.entrySet()) {
                
                String path = this.path;
                System.out.println(path);
                for (String filename : ent.getValue()) {
                    
                    ImageRow ir = new ImageRow();
                    ir.filename.setText(filename);
                    ir.filelabel.setText(ent.getKey());
                    
                    System.out.println(path + "/" + filename);
                    
                    try {
                        Image rawImage = ImageIO.read(new File(
                                path + "/" + filename));
                        ir.rawImage.setIcon(new ImageIcon(rawImage));
                        this.rowData.add(ir);
                        this.data.add(new ImageData(
                                path + "/" + filename, ent.getKey()));
                        
                        loadedFiles++;
                        int progress = (int)(((double)loadedFiles/
                                        (double)FileHandler.NUM_FILES) * 100);
                        this.progressBar.setValue(progress);
                        this.progressBar.setString("Loading Images " + 
                                progress + "%");
                    } catch (IOException ex) {
                        Logger.getLogger(Main.class.getName())
                                .log(Level.SEVERE, null, ex);
                    }

                }
                
            }
            
            return null;
        }
        
    }
    
    class RunCbpWorker extends SwingWorker {
        private JPanel imagePanel;
        private JProgressBar progressBar;
        private List<ImageRow> rowData;
        private List<ImageData> data;
        
        public RunCbpWorker(JPanel imagePanel, 
                List<ImageData> data, List<ImageRow> rowData, 
                JProgressBar progressBar) {
            this.imagePanel = imagePanel;
            this.progressBar = progressBar;
            this.rowData = rowData;
            this.data = data;
        }
        
        
        @Override
        protected void done() {
           
            JOptionPane.showMessageDialog(null, 
                    "All image successfully filtered", "Done", 
                    JOptionPane.INFORMATION_MESSAGE);
           for (int i = 0; i < this.data.size(); i++) {
               ImageData id = this.data.get(i);
               Image filteredImage = id.getBufferCbpImg();
               this.rowData.get(i).filteredImage
                       .setIcon(new ImageIcon(filteredImage));
           }
            
            repaint();
        }
        
        @Override
        protected Object doInBackground() throws Exception {
            int loadedFiles = 0;
            for (ImageData row : this.data) {
                loadedFiles++;
                int progress = (int)(((double)loadedFiles/
                                (double)this.data.size()) * 100);
                this.progressBar.setValue(progress);
                this.progressBar.setString("Cbp-ing Images " + 
                        progress + "%");
            }
            
            return null;
        }
        
    }
    
    class RunGaborWorker extends SwingWorker {

        private JPanel imagePanel;
        private JProgressBar progressBar;
        private List<ImageRow> rowData;
        private List<ImageData> data;
        private Mat kernel;
        
        public RunGaborWorker(Mat kernel, JPanel imagePanel, 
                List<ImageData> data, List<ImageRow> rowData, 
                JProgressBar progressBar) {
            this.imagePanel = imagePanel;
            this.progressBar = progressBar;
            this.rowData = rowData;
            this.data = data;
            this.kernel = kernel;
        }
        
        @Override
        protected void done() {
           
            JOptionPane.showMessageDialog(null, 
                    "All image successfully filtered", "Done", 
                    JOptionPane.INFORMATION_MESSAGE);
           for (int i = 0; i < this.data.size(); i++) {
               ImageData id = this.data.get(i);
               Image filteredImage = id.getBufferFilteredImg();
               this.rowData.get(i).filteredImage
                       .setIcon(new ImageIcon(filteredImage));
           }
            
            repaint();
        }
        
        @Override
        protected Object doInBackground() throws Exception {
            int loadedFiles = 0;
            for (ImageData row : this.data) {
                row.filterImg(this.kernel);
                loadedFiles++;
                int progress = (int)(((double)loadedFiles/
                                (double)this.data.size()) * 100);
                this.progressBar.setValue(progress);
                this.progressBar.setString("Filtering Images " + 
                        progress + "%");
            }
            
            return null;
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel classifiedRatio;
    private javax.swing.JSpinner epochField;
    private javax.swing.JPanel imageListPanel;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JTextField learningRateField;
    private javax.swing.JButton loadImageButton;
    private javax.swing.JButton loadImageProgramButton;
    private javax.swing.JLabel neuralNetworkLossChart;
    private javax.swing.JProgressBar neuralNetworkProgressBar;
    private javax.swing.JTable nnResultTable;
    private javax.swing.JPanel outputNeuronLogPanel;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTable resultProgramTable;
    private javax.swing.JButton runGaborButton;
    private javax.swing.JButton runNeuralNetworkAcoProgramButton;
    private javax.swing.JButton runNeuralNetworkButton;
    private javax.swing.JButton runNeuralNetworkProgramButton;
    private javax.swing.JTextField splitRatioText;
    // End of variables declaration//GEN-END:variables
}
